// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipsqnanrvceotncysjcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlwc3FuYW5ydmNlb3RuY3lzamNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxNzM3MTAsImV4cCI6MjA0OTc0OTcxMH0.iWMuDPx_QBJmgft9idIkon-zqIOcJca_0K4a4vZz6GM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);